In [3]:
import torch
import torch.nn as nn
import math

In [50]:
max_len = 512
d_model = 8
position = torch.arange(max_len).unsqueeze(1)
div_term = torch.exp(torch.arange(1, d_model + 1) * (-math.log(10000.0) / d_model))
pe = torch.zeros(1, max_len, d_model)
pe[0, :, 0::2] = torch.sin(position * div_term[0::2])
pe[0, :, 1::2] = torch.cos(position * div_term[1::2])

In [51]:
div_term

tensor([3.1623e-01, 1.0000e-01, 3.1623e-02, 1.0000e-02, 3.1623e-03, 1.0000e-03,
        3.1623e-04, 1.0000e-04])

In [52]:
pe.size()

torch.Size([1, 512, 8])

In [58]:
batch_size = 3
seq_len = 2
x=torch.rand(batch_size, seq_len, d_model)
print(x)
print(x.size(1))
print(pe[:, :x.size(1), :].size())
print(pe[:, :x.size(1), :])

print((x+pe[:, :x.size(1), :]).size())
print((x+pe[:, :x.size(1), :]))



tensor([[[0.7562, 0.0939, 0.1307, 0.6869, 0.8272, 0.2827, 0.5670, 0.1776],
         [0.0409, 0.2632, 0.1175, 0.4220, 0.8651, 0.8933, 0.6304, 0.2077]],

        [[0.0873, 0.7819, 0.4462, 0.2584, 0.2423, 0.1469, 0.8953, 0.6577],
         [0.3628, 0.3104, 0.9970, 0.1913, 0.0497, 0.3437, 0.0345, 0.6546]],

        [[0.6783, 0.4594, 0.9055, 0.6053, 0.0808, 0.5064, 0.2251, 0.3358],
         [0.7039, 0.5777, 0.1183, 0.1544, 0.7853, 0.8310, 0.5618, 0.5942]]])
2
torch.Size([1, 2, 8])
tensor([[[0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
          1.0000e+00, 0.0000e+00, 1.0000e+00],
         [3.1098e-01, 9.9500e-01, 3.1618e-02, 9.9995e-01, 3.1623e-03,
          1.0000e+00, 3.1623e-04, 1.0000e+00]]])
torch.Size([3, 2, 8])
tensor([[[0.7562, 1.0939, 0.1307, 1.6869, 0.8272, 1.2827, 0.5670, 1.1776],
         [0.3519, 1.2582, 0.1491, 1.4219, 0.8682, 1.8933, 0.6307, 1.2077]],

        [[0.0873, 1.7819, 0.4462, 1.2584, 0.2423, 1.1469, 0.8953, 1.6577],
         [0.6738, 1.3054, 1.0286, 1